### PR TITLE
Relaxed requirement on rake to include new rake 12.x

### LINKED ISSUE #77: Dependency on Rake <12 causing difficulties with ruby 2.4
Hi,

Ruby 2.4 comes with rake 12.0.0, but according to the Rakefile, hoe is incompatible with rake 12. Is it possible to relax this requirement or are there still-existing reasons for it? I am completely ignorant of the history here, apologies if this question is naive.

Thanks, and happy new year. ben

### PR DESCRIPTION
**Pull request by wwood**
Fixes #77.

### CODE REVIEW

**Comment by wwood** [comment]
I tested a variant of this patch within the GNU Guix package manager so that dependencies were built and where possible their unit tests were run, and didn't come across any issues after building >50 downstream packages.

i also checked the git blame, and the last commit on this line seems similar to that proposed here - https://github.com/seattlerb/hoe/commit/1e884305ed4c8104522314ac73fa1279f39e3bb9

**Comment by magnolia-k** [comment]
Is there a necessity to set a limit on rake's version?
There is no need to specify the version which does not exist at the present time as the upper limit, I think that it is good simply to designate it as 0.8 or more.

**Comment by wwood** [comment]
I set a requirement <13 because that was what was done previously. I'll leave it to the maintainer(s) to decide whether that is appropriate or not.

**Comment by zenspider** [comment]
@magnolia-k unbound dependency? no thank you. That's a recipe for disaster.

http://www.zenspider.com/ruby/2008/10/rubygems-how-to-preventing-catastrophe.html

**Comment by zenspider** [comment]
This is merged. Thanks!

**Comment by magnolia-k** [comment]
@zenspider 

I understood. Thanks.

**Comment by wwood** [comment]
Thanks, I see this is now released as 3.16.0 too. Might be worth closing #75 too, since that is the same patch.

**Pull request closed without merging**
